### ISSUE TITLE
[Question] Number sequences, use of ocamlformat and cinaps

### ISSUE THREAD

**Issue by darrenldl** [c-cube/oseq#13]
There are 2 questions in total in their individual sections below.

## 1. Prebuilt number sequences?

I've found myself needing number sequences quite frequently, and reckon it'd be nice if OSeq comes with prebuilt ones.

I'm adding some right now and intended to make it into a PR later, which will include the following sequences
- naturals
- arithmetic
- geometric (positive and integral ratio)
- odd numbers (positive, negative)
- even numbers (positive, negative)
- zero to n (exclusive, inclusive)
- range (exclusive, inclusive)

**Q**: Do you think prebuilt number sequences is useful and within the scope of OSeq? Or is it a better idea that I create another package just for number sequences?

EDIT: I read the doc again and realised above can be easily implemented using `take`, `cycle`, `iterate`, so maybe they aren't useful as prebuilts, but I'll wait for an answer to confirm anyhow.

## 2. Use of ocamlformat and cinaps?

If the answer to Q1 is positive (i.e. you'll accept the PR), then do you accept use of cinaps (and consequently ocamlformat) for the project?

I intend to have both int64 and int versions for the above sequences, and reckon using Cinaps for code generation would minimise human errors and code copy+pasting. As a direct result, ocamlformat is needed to make sure committed code is readable.

I am guessing ocamlformat is not used in OSeq purely because I don't seem to see ocamlformat used in the Makefile, which may be way off.

**Comment by c-cube** [comment]
1. I think it'd be better as a separate library (although possibly in the same repo), like `OSeq_num_sequences` or something like that. It can have its own opam package :slightly_smiling_face: . There is already a basic range operator I think?

2. ocamlformat irks me for now, cinaps is a no go (`ocaml >= 4.07`‽‽‽). I'd suggest to provide a functor parametrized by a simple number implementation and instances for `int` and `int64`. This way it's also easy to use it with `Z.t` if one has a fast-growing number sequence.

**Comment by darrenldl** [comment]
Thanks for the reply!

1. Yep makes sense - I might put it under a separate repository though, seeing our different preferences w.r.t. use of ocamlformat.

2. Yep you're right, functor would work much better in this scenario, I'll go with that route, which would also allow me to add a float implementation easily as well, which some people might want.
