### ISSUE TITLE
API docs are not styled

### ISSUE THREAD

**Issue by yawaramin** [c-cube/oseq#15]
The odoc CSS is not applying on the API docs: https://c-cube.github.io/oseq/oseq/OSeq/index.html

This is due to a teeny-tiny behaviour change in odoc which GitHub Pages doesn't like--they started using a directory called `_odoc_support` to contain all the support files (including CSS), and GitHub Pages by default ignores any directories starting with `_`.

Can be fixed easily by just adding an empty file called `.nojekyll` in the root directory in the `gh-pages` branch.

**Comment by c-cube** [comment]
good call, thanks :)
