### ISSUE TITLE
n-fold cartesian product

### ISSUE THREAD

**Issue by nilsbecker** [c-cube/oseq#4]
would it be feasible and/or desirable to have a function of the type `'a t list -> 'a list t` that produces all possible combinations of elements from the sequences?

**Comment by nilsbecker** [comment]
possibly, extensions of the existing `product` to the case of 3, 4, 5, ... tuples may be interesting as well.

**Comment by nilsbecker** [comment]
(if interesting, the same could apply to the `Sequence` module)

**Comment by c-cube** [comment]
You mean something like https://github.com/c-cube/ocaml-containers/blob/33d3ee114c06976660de3e5aa59fa76b8b2bc282/src/core/CCList.ml#L522 ?
I'm not sure it can be implemented in `Sequence`, will have to think about it. It's definitely possible to add to `OSeq`. Would you make a PR? Otherwise I'll do it this week

**Comment by nilsbecker** [comment]
yes, my first suggestion was what you linked. i now think the second one, adding a few convenient functions for making product tuples with arbitrary types, would be equally useful. i believe the second one could be done by the user by nesting the existing `product` but that seems a bit cumbersome. 

not sure i can get around to making a PR soon.  if i do i will post here first to avoid duplicating efforts.

**Comment by nilsbecker** [comment]
i don't think i get what you mean -- the user combines sequences using a combinator provided by the library, or the implementation of `productN` functions in the library is simplified through the use of some combinator? (also, how does the combinator look?)

**Comment by c-cube** [comment]
I was thinking about that, but it might be the dual of what you want:

```ocaml
utop [4]: OSeq.(return (fun x y z w-> x,y,z,w) <*> of_list [1;2;3] <*> return "a" <*> of_list [true;false] <*> of_list [10;20]) |> OSeq.to_list;;
- : (int * string * bool * int) list =
[(1, "a", true, 10); (2, "a", true, 10); (2, "a", true, 20);
 (1, "a", true, 20); (2, "a", false, 20); (2, "a", false, 10);
 (1, "a", false, 20); (1, "a", false, 10); (3, "a", false, 20);
 (3, "a", false, 10); (3, "a", true, 20); (3, "a", true, 10)]
```

**Comment by nilsbecker** [comment]
that's pretty nifty! i would not have thought of this way of using currying and the application operator on my own. i think this does all i want but it would be good to mention this construction as an example somewhere in the docs, no? so let's say for a nested loop of three variables one would write 
`return (fun x y z -> x, y, z) <*> sx <*> sy <*> sz` . is this short and easy enough or would one still want `product3 sx sy sz` in addition?

**Comment by c-cube** [comment]
This is the classic applicative pattern, which I know from Haskell :smile:. The full product `'a t list -> 'a list t` (or `'a t t -> 'a t t`) is still more complicated than that, I'll add it if you don't feel like doing it.

I think `product3` (and its family) can be reasonably useful, in a separate PR
