### ISSUE TITLE
merge & dovetailing

### ISSUE THREAD

**Issue by benti** [c-cube/oseq#6]
Hi,

If I understand the documentation correctly, OSeq.merge is supposed to perform “dovetailing”, i.e. the resulting sequence should contain all the elements of the input sequences. This does not seem to work for infinite sequences, though.

For example if the input sequences are
```
(0,0), (0,1), (0,2), …
(1,0), (1,1), (1,2), …
(2,0), (2,1), (2,2), …
….
```
Then merge returns
```
(0,0), (1,0), (2,0), (3,0) , …
```
But I would expect the merge to look like
```
(0,0),(1,0),(0,1),(2,0),(1,1),(0,2),(3,0),(2,1),(1,2),(0,3),(4,0),(3,1),(2,2),(1,3),(0,4),…
```
If you agree, then I think line 657/658 in OSeq should be replaced by:
```
| Cons (g, tl') ->
  let q = F_queue.push g q in
  let g', q = F_queue.pop_exn q in
  yield_from g' q tl'
```
Then it would roughly give the above sequence (up to local permutations). I also have some code to give exactly the sequence above if you’d prefer that.

**Comment by c-cube** [comment]
Thank you for the issue. Let me try to assess that change.

- :+1:  it seems like the semantics people would expect when merging an infinite stream of streams 
- :+1: it will effectively enumerate all the pairs, unlike the current implementation
- :-1: it breaks compatibility (but that's probably not bad)
- :-1: it "favors" the first streams by yielding their elements earlier

I think the pros largely outweight the cons. A PR would be appreciated if you don't see anything to add to this list.

**Comment by benti** [comment]
I found two solutions to implement this. 

One will yield exactly the sequence
```
(0,0),(1,0),(0,1),(2,0),(1,1),(0,2),(3,0),(2,1),(1,2),(0,3),(4,0),(3,1),(2,2),(1,3),(0,4),…
```
but I need to use `List.fold_right` for this (which is less efficient if I understand this correctly).

The other solution yields a sequence in which the pattern is a bit more unpredictable, but I believe it's fully tail-recursive.

Which one would you prefer?

**Comment by c-cube** [comment]
I'm not sure I see why you need `fold_right`. Let me think about that for a second :)

**Comment by benti** [comment]
Your current implementation also uses `List.rev`, hidden inside `F_queue`.

**Comment by c-cube** [comment]
in an amortized way, yes. I'm working on a patch, I'll make a PR and ask you to review :slightly_smiling_face:

**Comment by benti** [comment]
Nice!

Here's a test that would not have passed before:
```
mem ~eq:(=) (3,5) (merge (iterate 0 succ |> map (fun i -> iterate 0 succ |> map (fun j -> (i, j)))))
```

**Comment by c-cube** [comment]
Perfect, it does indeed fail on master :100:
