### ISSUE TITLE
Documentation question for take_while, drop_while

### ISSUE THREAD

**Issue by hcarty** [c-cube/oseq#9]
`take_while` has the following entry in `oseq.mli`:
```ocaml
val take_while : ('a -> bool) -> 'a t -> 'a t
(** Take elements while they satisfy the predicate. The initial iterator
    itself is not to be used anymore after this. *)
```

The comment about using the initial iterator doesn't seem like it's always appropriate since a seq value is not drained* by traversal.  Is this a leftover doc comment from the sequence/iter library?

[*] With the caveat that an underlying source like a file or socket may have its contents drained during traversal

**Comment by c-cube** [comment]
quite possibly, yes. These comments could use a refresher.

**Comment by hcarty** [comment]
Thanks!
